# Generated by Django 4.1.3 on 2023-04-09 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koreandictionaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalword',
            name='han_viet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=255)),
                ('original_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example', to='koreandictionaryapp.originalword')),
            ],
        ),
    ]
