# Generated by Django 4.1.3 on 2023-04-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreandictionaryapp', '0002_originalword_han_viet_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullmeaning',
            name='example_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fullmeaning',
            name='example_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='originalword',
            name='pronounce',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Examples',
        ),
    ]
